import { Task, Project, Session, Capability, Skill, Activity, DashboardStats } from '@/types';

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Review and optimize database queries',
    description: 'Analyze slow queries in the production database and optimize them for better performance.',
    status: 'in-progress',
    priority: 'high',
    project: 'Performance Optimization',
    assignedTo: 'Mike Jr.',
    createdAt: new Date('2026-02-10T09:00:00Z'),
    updatedAt: new Date('2026-02-11T14:30:00Z'),
    dueDate: new Date('2026-02-15T18:00:00Z'),
    tags: ['backend', 'database', 'performance'],
  },
  {
    id: 'task-2',
    title: 'Implement authentication flow',
    description: 'Add OAuth2 authentication with support for Google and GitHub providers.',
    status: 'todo',
    priority: 'urgent',
    project: 'Platform v2',
    createdAt: new Date('2026-02-11T08:00:00Z'),
    updatedAt: new Date('2026-02-11T08:00:00Z'),
    dueDate: new Date('2026-02-13T18:00:00Z'),
    tags: ['frontend', 'security', 'auth'],
  },
  {
    id: 'task-3',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints with examples and response schemas.',
    status: 'todo',
    priority: 'medium',
    project: 'Documentation',
    createdAt: new Date('2026-02-09T10:00:00Z'),
    updatedAt: new Date('2026-02-09T10:00:00Z'),
    tags: ['documentation', 'api'],
  },
  {
    id: 'task-4',
    title: 'Fix memory leak in worker process',
    description: 'Investigate and fix memory leak causing worker processes to crash after 24 hours.',
    status: 'blocked',
    priority: 'high',
    project: 'Platform v2',
    createdAt: new Date('2026-02-08T11:00:00Z'),
    updatedAt: new Date('2026-02-10T16:00:00Z'),
    tags: ['backend', 'bug', 'performance'],
  },
  {
    id: 'task-5',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment.',
    status: 'completed',
    priority: 'high',
    project: 'Infrastructure',
    createdAt: new Date('2026-02-05T09:00:00Z'),
    updatedAt: new Date('2026-02-08T15:00:00Z'),
    tags: ['devops', 'automation'],
  },
  {
    id: 'task-6',
    title: 'Design dashboard UI',
    description: 'Create wireframes and high-fidelity mockups for the admin dashboard.',
    status: 'completed',
    priority: 'medium',
    project: 'Platform v2',
    createdAt: new Date('2026-02-06T14:00:00Z'),
    updatedAt: new Date('2026-02-09T11:00:00Z'),
    tags: ['design', 'ui'],
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Platform v2',
    description: 'Complete rewrite of the platform with new architecture and improved performance.',
    status: 'active',
    progress: 65,
    tasks: mockTasks.filter(t => t.project === 'Platform v2'),
    createdAt: new Date('2026-01-15T09:00:00Z'),
    lastActivity: new Date('2026-02-11T14:30:00Z'),
    tags: ['frontend', 'backend', 'infrastructure'],
  },
  {
    id: 'proj-2',
    name: 'Performance Optimization',
    description: 'Optimize database queries, caching strategy, and API response times.',
    status: 'active',
    progress: 40,
    tasks: mockTasks.filter(t => t.project === 'Performance Optimization'),
    createdAt: new Date('2026-02-01T10:00:00Z'),
    lastActivity: new Date('2026-02-11T14:30:00Z'),
    tags: ['backend', 'database'],
  },
  {
    id: 'proj-3',
    name: 'Documentation',
    description: 'Comprehensive documentation for developers and end users.',
    status: 'active',
    progress: 25,
    tasks: mockTasks.filter(t => t.project === 'Documentation'),
    createdAt: new Date('2026-02-03T11:00:00Z'),
    lastActivity: new Date('2026-02-09T10:00:00Z'),
    tags: ['documentation'],
  },
  {
    id: 'proj-4',
    name: 'Infrastructure',
    description: 'Set up monitoring, logging, and CI/CD pipelines.',
    status: 'completed',
    progress: 100,
    tasks: mockTasks.filter(t => t.project === 'Infrastructure'),
    createdAt: new Date('2026-01-20T09:00:00Z'),
    lastActivity: new Date('2026-02-08T15:00:00Z'),
    tags: ['devops', 'infrastructure'],
  },
];

export const mockSessions: Session[] = [
  {
    id: 'session-1',
    startTime: new Date('2026-02-11T21:30:00Z'),
    endTime: new Date('2026-02-11T22:15:00Z'),
    duration: 2700,
    channel: 'Telegram',
    messages: 24,
    tasksCreated: 2,
    tasksCompleted: 1,
    summary: 'Built React dashboard structure and started implementing task tracking features.',
    tags: ['development', 'dashboard'],
  },
  {
    id: 'session-2',
    startTime: new Date('2026-02-11T18:00:00Z'),
    endTime: new Date('2026-02-11T18:45:00Z'),
    duration: 2700,
    channel: 'Telegram',
    messages: 18,
    tasksCreated: 1,
    tasksCompleted: 3,
    summary: 'Reviewed code quality issues and fixed linting errors.',
    tags: ['code-review', 'maintenance'],
  },
  {
    id: 'session-3',
    startTime: new Date('2026-02-10T14:00:00Z'),
    endTime: new Date('2026-02-10T16:30:00Z'),
    duration: 9000,
    channel: 'Telegram',
    messages: 67,
    tasksCreated: 4,
    tasksCompleted: 2,
    summary: 'Worked on database optimization tasks and performance analysis.',
    tags: ['backend', 'database', 'performance'],
  },
  {
    id: 'session-4',
    startTime: new Date('2026-02-09T10:00:00Z'),
    endTime: new Date('2026-02-09T11:30:00Z'),
    duration: 5400,
    channel: 'Telegram',
    messages: 31,
    tasksCreated: 2,
    tasksCompleted: 1,
    summary: 'Documentation planning and API endpoint design.',
    tags: ['documentation', 'planning'],
  },
  {
    id: 'session-5',
    startTime: new Date('2026-02-08T09:00:00Z'),
    endTime: new Date('2026-02-08T10:00:00Z'),
    duration: 3600,
    channel: 'Telegram',
    messages: 22,
    tasksCreated: 0,
    tasksCompleted: 2,
    summary: 'Bug triage and prioritization for Platform v2.',
    tags: ['bug-tracking', 'planning'],
  },
];

export const mockCapabilities: Capability[] = [
  {
    id: 'cap-1',
    name: 'Code Generation',
    category: 'Development',
    description: 'Generate production-ready code in various programming languages.',
    status: 'available',
    usageCount: 156,
    lastUsed: new Date('2026-02-11T22:15:00Z'),
  },
  {
    id: 'cap-2',
    name: 'Code Review',
    category: 'Development',
    description: 'Review code for bugs, security issues, and best practices.',
    status: 'available',
    usageCount: 89,
    lastUsed: new Date('2026-02-11T18:45:00Z'),
  },
  {
    id: 'cap-3',
    name: 'Documentation Writing',
    category: 'Writing',
    description: 'Create comprehensive documentation for code, APIs, and projects.',
    status: 'available',
    usageCount: 67,
    lastUsed: new Date('2026-02-09T11:30:00Z'),
  },
  {
    id: 'cap-4',
    name: 'Task Planning',
    category: 'Productivity',
    description: 'Break down complex projects into manageable tasks and prioritize them.',
    status: 'available',
    usageCount: 234,
    lastUsed: new Date('2026-02-11T14:30:00Z'),
  },
  {
    id: 'cap-5',
    name: 'Research & Analysis',
    category: 'Research',
    description: 'Research technical topics and analyze information for decision making.',
    status: 'available',
    usageCount: 112,
    lastUsed: new Date('2026-02-10T16:30:00Z'),
  },
  {
    id: 'cap-6',
    name: 'Debugging',
    category: 'Development',
    description: 'Analyze and fix bugs in code through systematic debugging.',
    status: 'available',
    usageCount: 78,
    lastUsed: new Date('2026-02-08T10:00:00Z'),
  },
  {
    id: 'cap-7',
    name: 'Data Analysis',
    category: 'Analysis',
    description: 'Analyze datasets and provide insights with visualizations.',
    status: 'learning',
    usageCount: 23,
    lastUsed: new Date('2026-02-05T14:00:00Z'),
  },
  {
    id: 'cap-8',
    name: 'System Architecture',
    category: 'Design',
    description: 'Design scalable and maintainable system architectures.',
    status: 'available',
    usageCount: 45,
    lastUsed: new Date('2026-02-06T10:00:00Z'),
  },
];

export const mockSkills: Skill[] = [
  {
    id: 'skill-1',
    name: 'TypeScript',
    description: 'Strong proficiency in TypeScript with advanced type system knowledge.',
    proficiency: 90,
    category: 'Programming Languages',
    examples: ['Generic type definitions', 'Utility types', 'Type guards', 'Inference'],
  },
  {
    id: 'skill-2',
    name: 'React/Next.js',
    description: 'Expert in React and Next.js with extensive production experience.',
    proficiency: 88,
    category: 'Frameworks',
    examples: ['SSR/SSG patterns', 'Custom hooks', 'Performance optimization', 'Testing'],
  },
  {
    id: 'skill-3',
    name: 'Node.js',
    description: 'Proficient in Node.js backend development and API design.',
    proficiency: 82,
    category: 'Backend',
    examples: ['Express.js', 'Fastify', 'API design', 'Middleware'],
  },
  {
    id: 'skill-4',
    name: 'Database Design',
    description: 'Skilled in database schema design and query optimization.',
    proficiency: 75,
    category: 'Data',
    examples: ['PostgreSQL', 'MongoDB', 'Query optimization', 'Indexing'],
  },
  {
    id: 'skill-5',
    name: 'DevOps/CI/CD',
    description: 'Knowledgeable about DevOps practices and CI/CD pipelines.',
    proficiency: 68,
    category: 'Operations',
    examples: ['GitHub Actions', 'Docker', 'Kubernetes', 'Monitoring'],
  },
  {
    id: 'skill-6',
    name: 'Testing',
    description: 'Experienced with various testing methodologies and frameworks.',
    proficiency: 72,
    category: 'Quality Assurance',
    examples: ['Unit tests', 'Integration tests', 'E2E tests', 'TDD'],
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    type: 'task',
    description: 'Created task "Implement authentication flow"',
    timestamp: new Date('2026-02-11T22:00:00Z'),
    details: { taskId: 'task-2', priority: 'urgent' },
  },
  {
    id: 'act-2',
    type: 'session',
    description: 'Session completed - Built React dashboard structure',
    timestamp: new Date('2026-02-11T22:15:00Z'),
    details: { sessionId: 'session-1', duration: 2700, messages: 24 },
  },
  {
    id: 'act-3',
    type: 'task',
    description: 'Updated task "Review and optimize database queries" to in-progress',
    timestamp: new Date('2026-02-11T14:30:00Z'),
    details: { taskId: 'task-1', oldStatus: 'todo', newStatus: 'in-progress' },
  },
  {
    id: 'act-4',
    type: 'project',
    description: 'Updated Platform v2 progress to 65%',
    timestamp: new Date('2026-02-11T14:30:00Z'),
    details: { projectId: 'proj-1', progress: 65 },
  },
  {
    id: 'act-5',
    type: 'task',
    description: 'Completed task "Set up CI/CD pipeline"',
    timestamp: new Date('2026-02-08T15:00:00Z'),
    details: { taskId: 'task-5' },
  },
];

export const mockStats: DashboardStats = {
  totalTasks: mockTasks.length,
  activeTasks: mockTasks.filter(t => t.status === 'in-progress').length,
  completedTasks: mockTasks.filter(t => t.status === 'completed').length,
  totalProjects: mockProjects.length,
  activeProjects: mockProjects.filter(p => p.status === 'active').length,
  totalSessions: mockSessions.length,
  recentSessions: mockSessions.filter(s => {
    const dayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    return s.startTime >= dayAgo;
  }).length,
  capabilitiesAvailable: mockCapabilities.filter(c => c.status === 'available').length,
};
